<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
 Schema::table('users',fn(Blueprint $t)=>$t->string('cfdt_role',20)->nullable()->after('administrative_work_menu_enabled')->index());
 Schema::create('cfdt_courses',function(Blueprint $t){$t->id();$t->string('code')->unique();$t->string('title');$t->text('description')->nullable();$t->json('content')->nullable();$t->json('questions')->nullable();$t->unsignedTinyInteger('pass_mark')->default(70);$t->unsignedTinyInteger('max_attempts')->default(3);$t->unsignedInteger('duration_minutes')->nullable();$t->string('status')->default('draft')->index();$t->foreignId('created_by')->constrained('users');$t->foreignId('validated_by')->nullable()->constrained('users');$t->timestamp('published_at')->nullable();$t->timestamps();});
 Schema::create('cfdt_enrollments',function(Blueprint $t){$t->id();$t->foreignId('course_id')->constrained('cfdt_courses')->cascadeOnDelete();$t->foreignId('user_id')->constrained('users')->cascadeOnDelete();$t->foreignId('assigned_by')->constrained('users');$t->timestamp('assigned_at');$t->timestamp('completed_at')->nullable();$t->unsignedTinyInteger('progress')->default(0);$t->string('status')->default('assigned');$t->timestamps();$t->unique(['course_id','user_id']);});
 Schema::create('cfdt_attempts',function(Blueprint $t){$t->id();$t->foreignId('enrollment_id')->constrained('cfdt_enrollments')->cascadeOnDelete();$t->json('question_snapshot');$t->json('answers');$t->unsignedSmallInteger('score')->default(0);$t->unsignedSmallInteger('total')->default(0);$t->decimal('percentage',5,2)->default(0);$t->boolean('passed')->default(false);$t->timestamp('started_at');$t->timestamp('submitted_at')->nullable();$t->timestamps();});
 Schema::create('cfdt_certificates',function(Blueprint $t){$t->id();$t->foreignId('enrollment_id')->unique()->constrained('cfdt_enrollments')->cascadeOnDelete();$t->uuid('verification_token')->unique();$t->string('number')->unique();$t->decimal('score',5,2);$t->timestamp('issued_at');$t->string('signature_hash',64);$t->timestamps();});
 } public function down():void{Schema::dropIfExists('cfdt_certificates');Schema::dropIfExists('cfdt_attempts');Schema::dropIfExists('cfdt_enrollments');Schema::dropIfExists('cfdt_courses');Schema::table('users',fn(Blueprint $t)=>$t->dropColumn('cfdt_role'));}};
