<?php
namespace App\Http\Controllers;
use App\Models\{CfdtAttempt,CfdtCertificate,CfdtCourse,CfdtEnrollment,User};
use Barryvdh\DomPDF\Facade\Pdf; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\Rule;
class CfdtController extends Controller {
 public function index(Request $r){$this->guard($r);$courses=CfdtCourse::when(!$r->user()->canManageCfdt(),fn($q)=>$q->where('status','published'))->withCount('enrollments')->latest()->get();$enrollments=CfdtEnrollment::with(['course','certificate'])->where('user_id',$r->user()->id)->get();return view('cfdt.index',compact('courses','enrollments'));}
 public function store(Request $r){abort_unless($r->user()->canManageCfdt(),403);$d=$r->validate(['code'=>'required|max:50|unique:cfdt_courses','title'=>'required|max:255','description'=>'nullable','duration_minutes'=>'nullable|integer|min:1','pass_mark'=>'required|integer|between:1,100','max_attempts'=>'required|integer|between:1,10','content'=>'nullable']);$d['content']=[['title'=>'Support principal','body'=>$d['content']??'']];unset($d['content']);$c=CfdtCourse::create([...$d,'content'=>[['title'=>'Support principal','body'=>$r->input('content')]],'questions'=>[],'created_by'=>$r->user()->id]);return redirect()->route('cfdt.show',$c);}
 public function show(Request $r,CfdtCourse $course){$this->guard($r);$enrollment=CfdtEnrollment::with(['attempts','certificate'])->where(['course_id'=>$course->id,'user_id'=>$r->user()->id])->first();$users=$r->user()->canManageCfdt()?User::where('active',true)->whereNotNull('cfdt_role')->orderBy('name')->orderBy('prenom')->get():collect();return view('cfdt.show',compact('course','enrollment','users'));}
 public function question(Request $r,CfdtCourse $course){abort_unless($r->user()->canManageCfdt(),403);$d=$r->validate(['text'=>'required','type'=>['required',Rule::in(['single','multiple'])],'options'=>'required|array|min:2','correct'=>'required|array|min:1','explanation'=>'nullable','points'=>'required|integer|min:1']);$qs=$course->questions??[];$qs[]=[...$d,'id'=>(string)Str::uuid()];$course->update(['questions'=>$qs]);return back()->with('status','Question ajoutée.');}
 public function publish(Request $r,CfdtCourse $course){abort_unless($r->user()->isInstitutionalSuperAdmin()||in_array($r->user()->cfdt_role,['validator','administrator']),403);abort_if(empty($course->questions),422,'Ajoutez au moins une question.');$course->update(['status'=>'published','validated_by'=>$r->user()->id,'published_at'=>now()]);return back()->with('status','Formation publiée.');}
 public function enroll(Request $r,CfdtCourse $course){abort_unless($r->user()->canManageCfdt(),403);$d=$r->validate(['user_ids'=>'required|array','user_ids.*'=>'exists:users,id']);foreach($d['user_ids'] as $id)CfdtEnrollment::firstOrCreate(['course_id'=>$course->id,'user_id'=>$id],['assigned_by'=>$r->user()->id,'assigned_at'=>now()]);return back()->with('status','Agents affectés.');}
 public function attempt(Request $r,CfdtCourse $course){$this->guard($r);$e=CfdtEnrollment::where(['course_id'=>$course->id,'user_id'=>$r->user()->id])->firstOrFail();abort_if($e->attempts()->count()>=$course->max_attempts,403,'Nombre maximal de tentatives atteint.');return view('cfdt.attempt',compact('course','e'));}
 public function submit(Request $r,CfdtCourse $course){$this->guard($r);$e=CfdtEnrollment::where(['course_id'=>$course->id,'user_id'=>$r->user()->id])->firstOrFail();abort_if($e->attempts()->count()>=$course->max_attempts,403);$answers=$r->input('answers',[]);$score=$total=0;foreach($course->questions as $q){$pts=(int)$q['points'];$total+=$pts;$given=(array)($answers[$q['id']]??[]);sort($given);$correct=(array)$q['correct'];sort($correct);if($given===$correct)$score+=$pts;}$pct=$total?round($score*100/$total,2):0;$passed=$pct >= $course->pass_mark;DB::transaction(function()use($e,$course,$answers,$score,$total,$pct,$passed){CfdtAttempt::create(['enrollment_id'=>$e->id,'question_snapshot'=>$course->questions,'answers'=>$answers,'score'=>$score,'total'=>$total,'percentage'=>$pct,'passed'=>$passed,'started_at'=>now(),'submitted_at'=>now()]);if($passed){$e->update(['status'=>'completed','progress'=>100,'completed_at'=>now()]);$token=(string)Str::uuid();CfdtCertificate::firstOrCreate(['enrollment_id'=>$e->id],['verification_token'=>$token,'number'=>'CFDT-'.now()->format('Y').'-'.str_pad($e->id,6,'0',STR_PAD_LEFT),'score'=>$pct,'issued_at'=>now(),'signature_hash'=>hash('sha256',$token.'|'.$e->id.'|'.$pct)]);}});return redirect()->route('cfdt.show',$course)->with('status',$passed?'Réussite : certificat délivré.':'Seuil non atteint.');}
 public function certificate(Request $r,CfdtCertificate $certificate){$certificate->load('enrollment.user','enrollment.course');abort_unless($certificate->enrollment->user_id===$r->user()->id||$r->user()->canManageCfdt(),403);return Pdf::loadView('cfdt.certificate',compact('certificate'))->download($certificate->number.'.pdf');}
 public function verify(string $token){$certificate=CfdtCertificate::with('enrollment.user','enrollment.course')->where('verification_token',$token)->firstOrFail();$expected=hash('sha256',$certificate->verification_token.'|'.$certificate->enrollment_id.'|'.$certificate->score);$valid=hash_equals($expected,$certificate->signature_hash);return view('cfdt.verify',compact('certificate','valid'));}
 private function guard(Request $r){abort_unless($r->user()->canAccessCfdt(),403);}
}
