<?php
namespace App\Http\Controllers;
use App\Models\{CfdtAttempt,CfdtCertificate,CfdtCourse,CfdtEnrollment,Department,User};
use App\Notifications\Cfdt\CfdtTestAssignedNotification;
use App\Support\UserRoles;
use Barryvdh\DomPDF\Facade\Pdf; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Log; use Illuminate\Support\Str; use Illuminate\Validation\Rule; use Illuminate\Validation\ValidationException;
class CfdtController extends Controller {
 public function index(Request $r){$this->guard($r);$courses=CfdtCourse::when(!$r->user()->canManageCfdt(),fn($q)=>$q->where('status','published'))->withCount('enrollments')->latest()->get();$enrollments=CfdtEnrollment::with(['course','certificate','attempts'])->where('user_id',$r->user()->id)->latest('assigned_at')->get();$completed=$enrollments->where('status','completed')->count();$average=$enrollments->flatMap->attempts->avg('percentage');return view('cfdt.index',compact('courses','enrollments','completed','average'));}
 public function store(Request $r){abort_unless($r->user()->canManageCfdt(),403);$d=$r->validate(['code'=>'required|max:50|unique:cfdt_courses','title'=>'required|max:255','description'=>'nullable','duration_minutes'=>'nullable|integer|min:1','pass_mark'=>'required|integer|between:1,100','max_attempts'=>'required|integer|between:1,10','content'=>'nullable']);$d['content']=[['title'=>'Support principal','body'=>$d['content']??'']];unset($d['content']);$c=CfdtCourse::create([...$d,'content'=>[['title'=>'Support principal','body'=>$r->input('content')]],'questions'=>[],'created_by'=>$r->user()->id]);return redirect()->route('cfdt.show',$c);}
 public function show(Request $r,CfdtCourse $course){$this->guard($r);$enrollment=CfdtEnrollment::with(['attempts','certificate'])->where(['course_id'=>$course->id,'user_id'=>$r->user()->id])->first();$users=$r->user()->canManageCfdt()?User::with('department')->where('active',true)->orderBy('name')->orderBy('prenom')->get():collect();$departments=$r->user()->canManageCfdt()?Department::where('active',true)->orderBy('name')->get():collect();$roleCategories=collect(UserRoles::all())->mapWithKeys(fn($role)=>[$role=>UserRoles::label($role)]);return view('cfdt.show',compact('course','enrollment','users','departments','roleCategories'));}
 public function question(Request $r,CfdtCourse $course){abort_unless($r->user()->canManageCfdt(),403);$d=$r->validate(['text'=>'required','type'=>['required',Rule::in(['single','multiple'])],'options'=>'required|array|min:2','correct'=>'required|array|min:1','explanation'=>'nullable','points'=>'required|integer|min:1']);$qs=$course->questions??[];$qs[]=[...$d,'id'=>(string)Str::uuid()];$course->update(['questions'=>$qs]);return back()->with('status','Question ajoutée.');}
 public function publish(Request $r,CfdtCourse $course){abort_unless($r->user()->isInstitutionalSuperAdmin()||in_array($r->user()->cfdt_role,['validator','administrator']),403);abort_if(empty($course->questions),422,'Ajoutez au moins une question.');$course->update(['status'=>'published','validated_by'=>$r->user()->id,'published_at'=>now()]);return back()->with('status','Formation publiée.');}
 public function enroll(Request $r,CfdtCourse $course){abort_unless($r->user()->canManageCfdt(),403);$d=$r->validate(['user_ids'=>'nullable|array','user_ids.*'=>'exists:users,id','department_ids'=>'nullable|array','department_ids.*'=>'exists:departments,id','role_categories'=>'nullable|array','role_categories.*'=>['string',Rule::in(UserRoles::all())],'include_descendants'=>'nullable|boolean','expires_at'=>'required|date|after:now']);if(empty($d['user_ids'])&&empty($d['department_ids'])&&empty($d['role_categories'])){throw ValidationException::withMessages(['audience'=>'Sélectionnez au moins un agent, une structure ou une fonction.']);}$departmentIds=array_map('intval',$d['department_ids']??[]);if($r->boolean('include_descendants')){$departmentIds=collect($departmentIds)->flatMap(fn($id)=>Department::subtreeIds($id))->unique()->values()->all();}$query=User::query()->where('active',true)->where(function($q)use($d,$departmentIds){$first=true;foreach([['id',$d['user_ids']??[]],['department_id',$departmentIds],['role',$d['role_categories']??[]]] as [$column,$values]){if(empty($values))continue;$first?$q->whereIn($column,$values):$q->orWhereIn($column,$values);$first=false;}});$targets=$query->get();if($targets->isEmpty()){throw ValidationException::withMessages(['audience'=>'Aucun agent actif ne correspond aux critères sélectionnés.']);}foreach($targets as $user){if($user->cfdt_role===null)$user->update(['cfdt_role'=>'learner']);$e=CfdtEnrollment::updateOrCreate(['course_id'=>$course->id,'user_id'=>$user->id],['assigned_by'=>$r->user()->id,'assigned_at'=>now(),'expires_at'=>$d['expires_at'],'invitation_token'=>(string)Str::uuid(),'notified_at'=>now(),'assignment_source'=>$this->assignmentSource($d),'assignment_context'=>['departments'=>$d['department_ids']??[],'roles'=>$d['role_categories']??[]]]);$e->load('course');$user->notify(new CfdtTestAssignedNotification($e));try{$user->notify(new CfdtTestAssignedNotification($e,true));}catch(\Throwable $exception){Log::warning('Échec invitation test CFDT par courriel.',['enrollment_id'=>$e->id,'error'=>$exception->getMessage()]);}}return back()->with('status',$targets->count().' agent(s) affecté(s). Les notifications internes ont été créées.');}
 public function invitation(Request $r,string $token){$e=CfdtEnrollment::with('course')->where('invitation_token',$token)->where('user_id',$r->user()->id)->firstOrFail();abort_if($e->isExpired(),403,'Ce lien d’invitation a expiré.');return redirect()->route('cfdt.show',$e->course);}
 public function attempt(Request $r,CfdtCourse $course){$this->guard($r);$e=CfdtEnrollment::where(['course_id'=>$course->id,'user_id'=>$r->user()->id])->firstOrFail();abort_if($e->isExpired(),403,'La date limite de ce test est dépassée.');abort_if($e->attempts()->count()>=$course->max_attempts,403,'Nombre maximal de tentatives atteint.');return view('cfdt.attempt',compact('course','e'));}
 public function submit(Request $r,CfdtCourse $course){$this->guard($r);$e=CfdtEnrollment::where(['course_id'=>$course->id,'user_id'=>$r->user()->id])->firstOrFail();abort_if($e->isExpired(),403,'La date limite de ce test est dépassée.');abort_if($e->attempts()->count()>=$course->max_attempts,403);$answers=$r->input('answers',[]);$score=$total=0;foreach($course->questions as $q){$pts=(int)$q['points'];$total+=$pts;$given=(array)($answers[$q['id']]??[]);sort($given);$correct=(array)$q['correct'];sort($correct);if($given===$correct)$score+=$pts;}$pct=$total?round($score*100/$total,2):0;$passed=$pct >= $course->pass_mark;DB::transaction(function()use($e,$course,$answers,$score,$total,$pct,$passed){CfdtAttempt::create(['enrollment_id'=>$e->id,'question_snapshot'=>$course->questions,'answers'=>$answers,'score'=>$score,'total'=>$total,'percentage'=>$pct,'passed'=>$passed,'started_at'=>now(),'submitted_at'=>now()]);if($passed){$e->update(['status'=>'completed','progress'=>100,'completed_at'=>now()]);$token=(string)Str::uuid();CfdtCertificate::firstOrCreate(['enrollment_id'=>$e->id],['verification_token'=>$token,'number'=>'CFDT-'.now()->format('Y').'-'.str_pad($e->id,6,'0',STR_PAD_LEFT),'score'=>$pct,'issued_at'=>now(),'signature_hash'=>hash('sha256',$token.'|'.$e->id.'|'.$pct)]);}});return redirect()->route('cfdt.show',$course)->with('status',$passed?'Réussite : certificat délivré.':'Seuil non atteint.');}
 public function certificate(Request $r,CfdtCertificate $certificate){$certificate->load('enrollment.user','enrollment.course');abort_unless($certificate->enrollment->user_id===$r->user()->id||$r->user()->canManageCfdt(),403);return Pdf::loadView('cfdt.certificate',compact('certificate'))->download($certificate->number.'.pdf');}
 public function verify(string $token){$certificate=CfdtCertificate::with('enrollment.user','enrollment.course')->where('verification_token',$token)->firstOrFail();$expected=hash('sha256',$certificate->verification_token.'|'.$certificate->enrollment_id.'|'.$certificate->score);$valid=hash_equals($expected,$certificate->signature_hash);return view('cfdt.verify',compact('certificate','valid'));}
 private function guard(Request $r){abort_unless($r->user()->canAccessCfdt(),403);}
 private function assignmentSource(array $data):string{return !empty($data['department_ids'])?'structure':(!empty($data['role_categories'])?'fonction':'individuel');}
}
